### ISSUE TITLE
FATAL: Failed to create reference base dir

### ISSUE THREAD

**Issue by Floyd1229** [RitchieLabIGH/IRFinder#1]
Hello, 

I'm trying to build a reference directly using the Ensembl FTP link, but am getting an error saying BuildRef fails to create a reference base directory:

_[my_username]$ module load singularity-3.8.3-gcc-8.2.0-7y47d4c
[my_username]$ REFdir=/PATH_TO_DIR/IRFinder/REF
[my_username]$ singularity run IRFinder BuildRef -r ${REFdir} ftp://ftp.ensembl.org/pub/release-102/gtf/mus_musculus/Mus_musculus.GRCm38.102.gtf.gz_ 

**Launching reference build process. The full build might take hours.
Trying to fetch dna.primary_assembly and GTF based on:
ftp://ftp.ensembl.org/pub/release-102/gtf/mus_musculus/Mus_musculus.GRCm38.102.gtf.gz

FATAL: Failed to create reference base dir: /PATH_TO_DIR/IRFinder/REF**

Additional Info:
OS distro and version: 3.10.0-957.1.3.el7.x86_64
Singularity: 3.8.3
IRFinder: 2.0.0
Bedtools: 2.27.1
GCC: 4.8.5 20150623 (Red Hat 4.8.5-36)
GLIBC: 2.17
Perl: perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi
Samtools: samtools 1.9, Using htslib 1.9

Any help would be appreciated. Thank you!

**Comment by CloXD** [comment]
Hello,
the error is most likely depending on Singularity: as with Docker, you can indicate uncommon folders ( example: /work/ ) with the --bind arguments (https://sylabs.io/guides/latest/user-guide/bind_paths_and_mounts.html) or using the environmental 
variable SINGULARITY_BINDPATH ( I usually prefer this method, https://singularity-tutorial.github.io/05-bind-mounts/) before calling singularity.
```
module load singularity-3.8.3-gcc-8.2.0-7y47d4c
export SINGULARITY_BINDPATH=/PATH_TO_DIR/
REFdir=/PATH_TO_DIR/IRFinder/REF
singularity run IRFinder BuildRef -r ${REFdir} https://ftp.ensembl.org/pub/release-102/gtf/mus_musculus/Mus_musculus.GRCm38.102.gtf.gz
```
I hope this will solve your issue.
Cheers,
Claudio

**Comment by Floyd1229** [comment]
Hi Claudio,

Thank you: that fixed it!

**Comment by CloXD** [comment]
Great!
