### ISSUE TITLE
IRFinder compatibility Check 

### ISSUE THREAD

**Issue by anoopktiwari** [RitchieLabIGH/IRFinder#13]
Hi There,

Thanks for providing the fantastic tool.

There are two different pages of IRFinder available on Github, so I want to know If both the pages are the same or if there is any difference between these two pages.
link 1: https://github.com/williamritchie/IRFinder
link 2: https://github.com/RitchieLabIGH/IRFinder

Please help me to get the answer.

**Comment by CloXD** [comment]
Hello,
in the first few lines of the README.md file, you can find your answer. 
Cheers,
Claudio
