### ISSUE TITLE
Problem with IRFinderDiff

### ISSUE THREAD

**Issue by JYuyangLu** [RitchieLabIGH/IRFinder#21]
Dear Claudio,

I met a problem with IRFinderDiff. 
```
converting counts to integer mode
using pre-existing size factors
estimating dispersions
Error in checkForExperimentalReplicates(object, modelMatrix) : 

  The design matrix has the same number of samples and coefficients to fit,
  so estimation of dispersion is not possible. Treating samples
  as replicates was deprecated in v1.20 and no longer supported since v1.22.

Calls: DESeq ... estimateDispersions -> .local -> checkForExperimentalReplicates
Execution halted
```

Does it relate to the R package version or something else?

Best,
Yuyang

**Comment by JYuyangLu** [comment]
Hi  Claudio,

Thank you for your quick response.  I see. I included all the replicates I have, and now the program runs perfectly. BTW, I saw some boxplots in the output folder. I would like to confirm that are they as a subset of IR regions with significant p values?
Thank you!

Yuyang

**Comment by CloXD** [comment]
Hello Yuyang,
yes, exactly, those are the IRratios of the introns having adjusted p-value lower than 0.05.
Cheers,
Claudio
