### ISSUE TITLE
IRFinder Diff 

### ISSUE THREAD

**Issue by rezarahman12** [RitchieLabIGH/IRFinder#25]
Dear IRFinder-S developer team,
Thank you for building this nice tool. I followed the instructions for singularity installation.  I'm using our inhouse RNA-seq data to identify differential introns. IRFinder worked well for all the steps except when I'm trying to run the differential IR analysis, I'm getting Rscript not found. Below is my code-  

./IRFinder Diff   -g:TTX ./TTX1/IRFinder-IR-nondir.txt -g:TTX ./TTX2/IRFinder-IR-nondir.txt -g:TTX ./TTX3/IRFinder-IR-nondir.txt -g:CTR ./Ctr1/IRFinder-IR-nondir.txt -g:CTR ./Ctr2/IRFinder-IR-nondir.txt -g:CTR ./Ctr3/IRFinder-IR-nondir.txt -ir 0.05 -o results.dir
**Rscript not found.**
I'll highly appreciate how can I run the IRFinder Diff. 
I'll look forward to hearing at your earliest convenience.
Best wishes
Reza
The University of Queensland, Australia

**Comment by CloXD** [comment]
Hello Reza,
First of all, thank you for using IRFinder-S.
To help you, I would need to know what operative system you are using and what image, if the one generated using singularity build or the one you can download from here https://github.com/RitchieLabIGH/IRFinder/releases/tag/v2.0.1 .
If there is some conflict with the environmental variables, you could try:
```
singularity exec -e ./IRFinder Diff ...
```
Furthermore, there could be an error in R due to the loading of local libraries. You can avoid this by setting the home to an empty directory: 
```
mkdir ${HOME}/tmp_home/
singularity exec -e -H ${HOME}/tmp_home/ ./IRFinder Diff ....
```
I hope that one of those solutions will help.
Cheers,
Claudio

**Comment by rezarahman12** [comment]
Hi Claudio,
Thank you so much for your quick response. Yea, your suggestions helped. However, I had just need to modify a little bit
singularity exec -e ./IRFinder IRFinder Diff ...
Just one more clarification-
the results files created are given in the attached screenshot. Is that okay? or any other plot should be generated as well?
Thank you again and appreciate your time and help. 
Best wishes,
Reza
![image](https://github.com/RitchieLabIGH/IRFinder/assets/110575883/ee34d80e-27ea-4b3d-b83f-38012412687d)

**Comment by rezarahman12** [comment]
Hi Claudio
Thank you so much for your response. Is it possible to generate box plot of IR events based on p-value not FDR since IRFinder in the case of my data did not give any IR events passed FDR <0.05?

Thanks a lot again.
Best regards
Reza

**Comment by CloXD** [comment]
Dear Reza,
It's not possible using only the IRFinder method, but you can easily generate them using R or Python.
You can retrieve the IR ratios for each sample from the file all_results_DESeq2.tsv or from the original IRFinder-IR-nondir.txt files.
Cheers,
Claudio

**Comment by rezarahman12** [comment]
Thanks a lot, Claudio for your suggestions.
