### ISSUE TITLE
BuildRefProcess: limitGenomeGenerateRAM=31000000000is too small for your genome

### ISSUE THREAD

**Issue by Floyd1229** [RitchieLabIGH/IRFinder#3]
Hello,

I'm trying to build my IR Reference using downloaded FASTA and GTF files from GENCODE ([GRCm36.p6 build](https://www.gencodegenes.org/mouse/release_M20.html)). From this page, downloaded the GTF file = comprehensive gene annotation - ALL, and FASTA file =  Genome sequence (GRCm38.p6) - ALL, renamed them "transcripts.gtf" and "genome.fa" respectively, and put them in my reference folder. When running IRFinder's BuildRefProcess, I get an error saying I don't have enough RAM for the STAR Reference Preparation phase. 

I saw this issue for the prior IRFinder version ([GitHub BuildRefProcess does not complete #155](https://github.com/williamritchie/IRFinder/issues/155)), but it wasn't resolved? I'm working on slurm, and I requested 500G of working memory, which is usually enough whenever I run STAR alone. Is there any way to specify the genome generate RAM limit with the BuildRefProcess function? Or should I try something else?

Any help would be appreciated. Thank you.

```
[my_username]$ srun -n1 --pty --partition=panda --mem=500G bash -i
[my_username]$ module load singularity-3.8.3-gcc-8.2.0-7y47d4c
[my_username]$ export SINGULARITY_BINDPATH=/PATH_TO_DIR/

[my_username]$ REF2=/PATH_TO_REF2_DIR
[my_username]$ singularity run IRFinder BuildRefProcess -r ${REF2} 

Launching reference build process. The full build might take hours.
<Phase 1: STAR Reference Preparation>
	STAR --runMode genomeGenerate --genomeDir /PATH_TO_REF2_DIR/STAR --genomeFastaFiles /PATH_TO_REF2_DIR/genome.fa --sjdbGTFfile /PATH_TO_REF2_DIR/ranscripts.gtf --sjdbOverhang 150 --runThreadN 64 &>> log-star-build-ref.log
	STAR version: 2.7.9a   compiled: 2021-08-23T14:42:18+00:00 9eef339eb03c:/Utils/STAR/source
Jan 27 14:08:27 ..... started STAR run
Jan 27 14:08:27 ... starting to generate Genome files

EXITING because of FATAL PARAMETER ERROR: limitGenomeGenerateRAM=31000000000is too small for your genome
SOLUTION: please specify --limitGenomeGenerateRAM not less than 109857909685 and make that much RAM available 

Jan 27 14:09:08 ...... FATAL ERROR, exiting
Star genome build: Failed!
```

Additional Info:
OS distro and version: 3.10.0-957.1.3.el7.x86_64
Singularity: 3.8.3
IRFinder: 2.0.0
Bedtools: 2.27.1
GCC: 4.8.5 20150623 (Red Hat 4.8.5-36)
GLIBC: 2.17
Perl: perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi
Samtools: samtools 1.9, Using htslib 1.9

**Comment by CloXD** [comment]
Hello Floyd,
sorry for the inconvenience: it's concerning the argument "limitGenomeGenerateRAM" that is not specified in IRFinder. I'll fix the bug and rebuild the singularity image. In the meanwhile, you can try using only the primary assembly (Genome sequence, primary assembly (GRCm38) ), the dimension should be smaller and therefore it should work without any issue.
Cheers,
Claudio

**Comment by CloXD** [comment]
Done, now there is a -L argument with whom you can specify the STAR's limitGenomeGenerateRAM. 
Let me know if it solved the issue.
Cheers,
Claudio

**Comment by Floyd1229** [comment]
Hi Claudio, 

The -L argument works so far! Had to redownload the Singularity image then redo BuildRefProcess. 

Commands I ran: 
```
[my_username]$ srun -n1 --pty --partition=panda --mem=300G bash -i
[my_username]$ singularity build -F ./IRFinder docker://cloxd/irfinder:2.0
[my_username]$ module load singularity-3.8.3-gcc-8.2.0-7y47d4c
[my_username]$ export SINGULARITY_BINDPATH=/PATH_TO_DIR/

[my_username]$ REF2=/PATH_TO_REF2_DIR
[my_username]$ singularity run IRFinder BuildRefProcess -r ${REF2} -L 109857909685
```
