### ISSUE TITLE
Adaptor trimming option

### ISSUE THREAD

**Issue by rezarahman12** [RitchieLabIGH/IRFinder#33]
Hello IRFinder team,

Thanks for building this excellent software. I'm trying to quantify intron retention from my fastq files. Since the fastq file has Illumina standard adaptor, so I want to run so that the adaptor gets trimmed. 

Please see my below command-
../IRFinder FastQ -r /scratch/project_mnt/S0077/IRFinder/ReferenceDir -d 24h_Ctr1 \
-a AGATCGGAAG AGATCGGAAG /scratch/project_mnt/S0077/scaling_birectional/fastq/intron_retention/rawdata/Ctr24h_1_1.fq /scratch/project_mnt/S0077/scaling_birectional/fastq/intron_retention/rawdata/Ctr24h_1_2.fq

I'm getting below error-
Argument error: in run mode FastQ, provide either one or two fastq files. 3 arguments found.

Please guide me how to overcome this problem.

Thanks for your kind consideration.

Best regards
Reza

**Comment by CloXD** [comment]
Hello Reza,
first of all, thanks for using IRFinder-S. The default Illumina adaptors are trimmed as default, so you can leave out that argument. If you want to specify it anyway, for paired end the two sequences have to be comma separated:
```
../IRFinder FastQ -r /scratch/project_mnt/S0077/IRFinder/ReferenceDir -d 24h_Ctr1
-a AGATCGGAAG,AGATCGGAAG /scratch/project_mnt/S0077/scaling_birectional/fastq/intron_retention/rawdata/Ctr24h_1_1.fq /scratch/project_mnt/S0077/scaling_birectional/fastq/intron_retention/rawdata/Ctr24h_1_2.fq

```

Cheers,
Claudio

**Comment by rezarahman12** [comment]
Hi Claudio,
Thanks for your quick response. I find it useful.
Best regards
Reza
