### ISSUE TITLE
Unable to load DESeq2 under singularity

### ISSUE THREAD

**Issue by glarue** [RitchieLabIGH/IRFinder#8]
I'm trying to run `IRFinder Diff` on Linux using `singularity run`, but it looks like it's sourcing the system-level `R` installation (from `log.err`):
```
Error: package or namespace load failed for 'DESeq2' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/glarue/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/libs/Rcpp.so':
  /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/glarue/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/libs/Rcpp.so)
Execution halted
```
I've tried running `singularity` with the `--cleanenv` flag, but it produces the same error. Any pointers would be appreciated!

**Comment by CloXD** [comment]
Hello,
sorry for the late answer. I'm fixing the problem and will be soon available with the new release ( v2.0.1 ).
Cheers,
Claudio
